# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeautifulMoviePy(object):
    def setupUi(self, BeautifulMoviePy):
        BeautifulMoviePy.setObjectName("BeautifulMoviePy")
        BeautifulMoviePy.resize(945, 672)
        self.title = QtWidgets.QLabel(BeautifulMoviePy)
        self.title.setGeometry(QtCore.QRect(50, 0, 441, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.Source = QtWidgets.QPushButton(BeautifulMoviePy)
        self.Source.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.target = QtWidgets.QPushButton(BeautifulMoviePy)
        self.target.setGeometry(QtCore.QRect(470, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.target.setFont(font)
        self.target.setObjectName("target")
        self.SourcePath = QtWidgets.QTextBrowser(BeautifulMoviePy)
        self.SourcePath.setGeometry(QtCore.QRect(120, 100, 341, 31))
        self.SourcePath.setObjectName("SourcePath")
        self.OutputPath = QtWidgets.QTextBrowser(BeautifulMoviePy)
        self.OutputPath.setGeometry(QtCore.QRect(580, 100, 341, 31))
        self.OutputPath.setObjectName("OutputPath")
        self.startOption = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.startOption.setGeometry(QtCore.QRect(20, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.startOption.setFont(font)
        self.startOption.setObjectName("startOption")
        self.endOption = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.endOption.setGeometry(QtCore.QRect(480, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.endOption.setFont(font)
        self.endOption.setObjectName("endOption")
        self.startTimes = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.startTimes.setGeometry(QtCore.QRect(120, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.startTimes.setFont(font)
        self.startTimes.setObjectName("startTimes")
        self.endTimes = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.endTimes.setGeometry(QtCore.QRect(580, 150, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.endTimes.setFont(font)
        self.endTimes.setObjectName("endTimes")
        self.fftOption = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.fftOption.setGeometry(QtCore.QRect(20, 190, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.fftOption.setFont(font)
        self.fftOption.setObjectName("fftOption")
        self.IncreaseV = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.IncreaseV.setGeometry(QtCore.QRect(20, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.IncreaseV.setFont(font)
        self.IncreaseV.setObjectName("IncreaseV")
        self.DecreaseV = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.DecreaseV.setGeometry(QtCore.QRect(440, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.DecreaseV.setFont(font)
        self.DecreaseV.setObjectName("DecreaseV")
        self.increaseInput = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.increaseInput.setGeometry(QtCore.QRect(210, 230, 141, 41))
        self.increaseInput.setObjectName("increaseInput")
        self.decreaseInput = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.decreaseInput.setGeometry(QtCore.QRect(630, 230, 141, 41))
        self.decreaseInput.setObjectName("decreaseInput")
        self.label = QtWidgets.QLabel(BeautifulMoviePy)
        self.label.setGeometry(QtCore.QRect(360, 250, 47, 12))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BeautifulMoviePy)
        self.label_2.setGeometry(QtCore.QRect(780, 250, 47, 12))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.toMP4 = QtWidgets.QPushButton(BeautifulMoviePy)
        self.toMP4.setGeometry(QtCore.QRect(240, 500, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.toMP4.setFont(font)
        self.toMP4.setObjectName("toMP4")
        self.toGIF = QtWidgets.QPushButton(BeautifulMoviePy)
        self.toGIF.setGeometry(QtCore.QRect(480, 500, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.toGIF.setFont(font)
        self.toGIF.setObjectName("toGIF")
        self.status = QtWidgets.QLabel(BeautifulMoviePy)
        self.status.setGeometry(QtCore.QRect(200, 590, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.subclip_concat = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.subclip_concat.setGeometry(QtCore.QRect(20, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.subclip_concat.setFont(font)
        self.subclip_concat.setObjectName("subclip_concat")
        self.subclip_seperate = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.subclip_seperate.setGeometry(QtCore.QRect(440, 270, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.subclip_seperate.setFont(font)
        self.subclip_seperate.setObjectName("subclip_seperate")
        self.subclipText = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.subclipText.setGeometry(QtCore.QRect(20, 310, 381, 171))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.subclipText.setFont(font)
        self.subclipText.setAccessibleDescription("")
        self.subclipText.setObjectName("subclipText")
        self.seperateText = QtWidgets.QTextEdit(BeautifulMoviePy)
        self.seperateText.setGeometry(QtCore.QRect(440, 310, 381, 171))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.seperateText.setFont(font)
        self.seperateText.setAccessibleDescription("")
        self.seperateText.setObjectName("seperateText")
        self.generateSerial = QtWidgets.QCheckBox(BeautifulMoviePy)
        self.generateSerial.setGeometry(QtCore.QRect(660, 480, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.generateSerial.setFont(font)
        self.generateSerial.setObjectName("generateSerial")

        self.retranslateUi(BeautifulMoviePy)
        QtCore.QMetaObject.connectSlotsByName(BeautifulMoviePy)

    def retranslateUi(self, BeautifulMoviePy):
        _translate = QtCore.QCoreApplication.translate
        BeautifulMoviePy.setWindowTitle(_translate("BeautifulMoviePy", "BeautifulMoviePy"))
        self.title.setText(_translate("BeautifulMoviePy", "BeautifulMoviePy"))
        self.Source.setText(_translate("BeautifulMoviePy", "Source Path"))
        self.target.setText(_translate("BeautifulMoviePy", "OutputPath"))
        self.startOption.setText(_translate("BeautifulMoviePy", "Start"))
        self.endOption.setText(_translate("BeautifulMoviePy", "End"))
        self.startTimes.setHtml(_translate("BeautifulMoviePy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\';\">example format:00:00:08</span></p></body></html>"))
        self.endTimes.setHtml(_translate("BeautifulMoviePy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'PMingLiU\';\">example format:00:17:40</span></p></body></html>"))
        self.fftOption.setText(_translate("BeautifulMoviePy", "remove silence audio(Beta)"))
        self.IncreaseV.setText(_translate("BeautifulMoviePy", "Increase Volume"))
        self.DecreaseV.setText(_translate("BeautifulMoviePy", "Decrease Volume"))
        self.label.setText(_translate("BeautifulMoviePy", "Times"))
        self.label_2.setText(_translate("BeautifulMoviePy", "Times"))
        self.toMP4.setText(_translate("BeautifulMoviePy", "->mp4"))
        self.toGIF.setText(_translate("BeautifulMoviePy", "->GIF"))
        self.subclip_concat.setText(_translate("BeautifulMoviePy", "subclips - concatnate"))
        self.subclip_seperate.setText(_translate("BeautifulMoviePy", "subclips - seperate"))
        self.subclipText.setHtml(_translate("BeautifulMoviePy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">example format:00:00:08~00:00:15</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.seperateText.setHtml(_translate("BeautifulMoviePy", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">example format:0001.mp4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(base on output path)</p></body></html>"))
        self.generateSerial.setText(_translate("BeautifulMoviePy", "generate filename by serial number"))
